<?php

/**
 * @file
 * Tide Media install.
 */

use Drupal\Component\Utility\NestedArray;
use Drupal\Core\Config\FileStorage;
use Drupal\field\Entity\FieldConfig;
use Drupal\tide_media\TideOperation;

/**
 * Implements hook_install().
 */
function tide_media_install() {
  TideOperation::enableStandaloneMedia();
  TideOperation::entityUsageDefaultSettings();
  TideOperation::assignNecessaryPermissions();
  TideOperation::createLicenseTypeTerms();

}

/**
 * Updates to have department field required.
 */
function tide_media_update_10001() {
  $entity_type = 'media';
  $media_bundles = \Drupal::service('entity_type.bundle.info')->getBundleInfo($entity_type);
  $bundles = [
    'audio',
    'document',
    'embedded_video',
    'file',
    'image',
  ];
  if (!empty($media_bundles) && is_array($media_bundles)) {
    foreach ($media_bundles as $name => $bundle) {
      if (in_array($name, $bundles)) {
        $field = FieldConfig::loadByName($entity_type, $name, 'field_media_department');
        if (!empty($field)) {
          $field->setRequired(TRUE);
          $field->save();
        }
      }
    }
  }
}

/**
 * Creates terms for license_type vocabulary for installed site.
 */
function tide_media_update_10002() {
  TideOperation::createLicenseTypeTerms();
}

/**
 * Remove the png icon.
 */
function tide_media_update_10003() {
  $config_factory = \Drupal::configFactory();
  $config = $config_factory->getEditable('embed.button.tide_media');
  $config->set('icon', [])->save();
}

/**
 * Enable Private files download permission module.
 */
function tide_media_update_10004() {
  if (!\Drupal::moduleHandler()->moduleExists('pfdp')) {
    /** @var \Drupal\Core\Extension\ModuleInstallerInterface $module_installer */
    $module_installer = \Drupal::service('module_installer');
    $module_installer->install(['pfdp']);

    $configs = [
      'pfdp.pfdp_directory.secure',
      'media.type.secure_file',
      'user.role.secure_file_user',
    ];

    $config_path = \Drupal::service('extension.list.module')->getPath('tide_media') . '/config/install';
    $source = new FileStorage($config_path);
    $config_storage = \Drupal::service('config.storage');

    foreach ($configs as $config) {
      $config_storage->write($config, $source->read($config));
    }

    // Add field.
    $field_configs = [
      'field.storage.media.field_secure_file' => 'field_storage_config',
      'field.field.media.secure_file.field_secure_file' => 'field_config',
    ];
    module_load_include('inc', 'tide_core', 'includes/helpers');
    $config_location = [\Drupal::service('extension.list.module')->getPath('tide_media') . '/config/install'];

    // Check if field already exported to config/sync.
    foreach ($field_configs as $config => $type) {
      $config_read = _tide_read_config($config, $config_location, TRUE);
      $storage = \Drupal::entityTypeManager()->getStorage($type);
      $id = substr($config, strrpos($config, '.') + 1);
      if ($storage->load($id) == NULL) {
        $config_entity = $storage->createFromStorageRecord($config_read);
        $config_entity->save();
      }
    }

    $update_configs = [
      'core.entity_form_display.media.secure_file.default' => 'entity_form_display',
      'core.entity_view_display.media.secure_file.default' => 'entity_view_display',
    ];
    $skipped_settings = [
      'uuid',
      'langcode',
      'status',
      '_core',
      'id',
      'field_name',
      'entity_type',
      'bundle',
      'label',
      'description',
      'required',
      'translatable',
      'field_type',
    ];
    foreach ($update_configs as $update_config => $type) {
      $config_read = _tide_read_config($update_config, $config_location, FALSE);
      $config = \Drupal::configFactory()->getEditable($update_config);
      if (!$config) {
        continue;
      }
      $data = $config->getRawData();
      foreach ($config_read as $key => $item) {
        if (in_array($key, $skipped_settings)) {
          continue;
        }
        NestedArray::setValue($data, [
          $key,
        ], NestedArray::getValue($config_read, [
          $key,
        ]));
      }
      $config->setData($data)->save();
    }
  }
}
