<?php

/**
 * @file
 * Tide Media Secure Files.
 */

/**
 * Implements hook_uninstall().
 */
function tide_media_secure_files_uninstall() {
}

/**
 * Implements hook_install().
 */
function tide_media_secure_files_install() {
  if (!\Drupal::moduleHandler()->moduleExists('pfdp')) {
    /** @var \Drupal\Core\Extension\ModuleInstallerInterface $module_installer */
    $module_installer = \Drupal::service('module_installer');
    $module_installer->install(['pfdp']);
  }
}

/**
 * Enable Private files download permission module.
 */
/* function tide_media_update_10004() {
  if (!\Drupal::moduleHandler()->moduleExists('pfdp')) {
    $module_installer = \Drupal::service('module_installer');
    $module_installer->install(['pfdp']);

    $configs = [
      'pfdp.pfdp_directory.secure',
      'media.type.secure_file',
      'user.role.secure_file_user',
    ];

    $config_path = \Drupal::service('extension.list.module')->getPath('tide_media') . '/config/install';
    $source = new FileStorage($config_path);
    $config_storage = \Drupal::service('config.storage');

    foreach ($configs as $config) {
      $config_storage->write($config, $source->read($config));
    }

    // Add field.
    $field_configs = [
      'field.storage.media.field_secure_file' => 'field_storage_config',
      'field.field.media.secure_file.field_secure_file' => 'field_config',
    ];
    module_load_include('inc', 'tide_core', 'includes/helpers');
    $config_location = [\Drupal::service('extension.list.module')->getPath('tide_media') . '/config/install'];

    // Check if field already exported to config/sync.
    foreach ($field_configs as $config => $type) {
      $config_read = _tide_read_config($config, $config_location, TRUE);
      $storage = \Drupal::entityTypeManager()->getStorage($type);
      $id = substr($config, strrpos($config, '.') + 1);
      if ($storage->load($id) == NULL) {
        $config_entity = $storage->createFromStorageRecord($config_read);
        $config_entity->save();
      }
    }

    $update_configs = [
      'core.entity_form_display.media.secure_file.default' => 'entity_form_display',
      'core.entity_view_display.media.secure_file.default' => 'entity_view_display',
    ];
    $skipped_settings = [
      'uuid',
      'langcode',
      'status',
      'id',
      'bundle',
    ];
    foreach ($update_configs as $update_config => $type) {
      $config_read = _tide_read_config($update_config, $config_location, FALSE);
      $config = \Drupal::configFactory()->getEditable($update_config);
      if (!$config) {
        continue;
      }
      $data = $config->getRawData();
      foreach ($config_read as $key => $item) {
        if (in_array($key, $skipped_settings)) {
          continue;
        }
        NestedArray::setValue($data, [
          $key,
        ], NestedArray::getValue($config_read, [
          $key,
        ]));
      }
      $config->setData($data)->save();
    }
  }
} */

